replicaCount: 1

image:
  repository: ghcr.io/wnsnaissante/kaidapi
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  name: kaidapi

ingress:
  enabled: true
  host: kaid.ceptrix.cloud
  ingressClassName: haproxy
  annotations:
    haproxy-ingress.github.io/ssl-redirect: "true"
    haproxy-ingress.github.io/ssl-backend: "false"
  tls:
    secretName: ceptrix-cloud-tls

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"
  - name: OpenIDConnectSettings__Authority
    value: "https://auth.ceptrix.cloud/application/o/ceptrix/"
  - name: OpenIDConnectSettings__ClientId
    value: "4M7U589KsfghGy3yrjIFFHIFaWaUa3kMsAcCPNUk"

secrets:
  enabled: true
  database:
    connectionString: ""
  jwt:
    secretKey: ""
  apiKeys:
    externalService: ""
  openIdConnect:
    authority: ""
    clientSecret: ""
    clientId: ""
    issuer: ""