replicaCount: 1

image:
  repository: ghcr.io/wnsnaissante/kaidapi
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: "Production"

secrets:
  enabled: true
  database:
    connectionString: ""
  jwt:
    secretKey: ""
  apiKeys:
    externalService: ""
  openIdConnect:
    authority: ""
    clientSecret: ""
    clientId: ""
    issuer: "" 