apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kaidapi.fullname" . }}-migration
  labels:
    {{- include "kaidapi.labels" . | nindent 4 }}
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dotnet", "ef", "database", "update", "--project", "KaidAPI/KaidAPI.csproj"]
          workingDir: /app
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
            {{- with .Values.env.extra }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "kaidapi.fullname" . }}-secrets
      restartPolicy: Never
  backoffLimit: 1 