{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.secrets.database.connectionString }}
  ConnectionStrings__MySql: {{ .Values.secrets.database.connectionString | b64enc }}
  {{- end }}
  {{- if .Values.secrets.openIdConnect.authority }}
  OpenIDConnectSettings__Authority: {{ .Values.secrets.openIdConnect.authority | b64enc }}
  {{- end }}
  {{- if .Values.secrets.openIdConnect.clientSecret }}
  OpenIDConnectSettings__ClientSecret: {{ .Values.secrets.openIdConnect.clientSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.openIdConnect.clientId }}
  OpenIDConnectSettings__ClientId: {{ .Values.secrets.openIdConnect.clientId | b64enc }}
  {{- end }}
  {{- if .Values.secrets.openIdConnect.issuer }}
  OpenIDConnectSettings__Issuer: {{ .Values.secrets.openIdConnect.issuer | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwt.secretKey }}
  JWT__SecretKey: {{ .Values.secrets.jwt.secretKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.apiKeys.externalService }}
  ExternalService__ApiKey: {{ .Values.secrets.apiKeys.externalService | b64enc }}
  {{- end }}
{{- end }} 